openapi: 3.0.3
info:
  title: Blog API Documentaition
  version: 0.0.1
servers:
  - url: http://localhost:8080
    description: Local Development Server
tags:
  - name: csrf-protection
    description: CSRF 攻撃対策の API
  - name: users
    description: ユーザー情報の API
  - name: login-logout
    description: ログインとログアウトの API
  - name: articles
    description: ブログ記事関連の API
paths:
  /csrf-cookie:
    get:
      tags: [ csrf-protection ]
      operationId: getCsrfCookie
      summary: CSRF Cookie の取得
      description: |
        リクエストに成功すると、204 No Content のレスポンスが返ります。
        このレスポンスの Set-Cookie ヘッダーに XSRF-TOKEN が含まれています。
        POST リクエストを実行するときは、受け取った XSRF-TOKEN の値を X-XSRF-TOKEN ヘッダーに設定する必要があります。
        XSRF-TOKEN の値は POST リクエストの度に取得し直す必要はなく、同じ値を何度も使うことができます。
      responses:
        '204':
          description: No Content
          headers:
            Set-Cookie:
              description: CSRF 対策に利用する XSRF-TOKEN という Cookie が含まれています
              schema:
                type: string
                example: XSRF-TOKEN=4ee8188f-2873-46cb-937f-7464ebf143e7; Path=/
          content: { }
        '500':
          $ref: "#/components/responses/InternalServerErrorResponse"
  /login:
    post:
      description: ログインをします
      tags: [ login-logout ]
      operationId: login
      security:
        - csrfProtectionHeader: [ ]
        - csrfProtectionCookie: [ ]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: username123
                password:
                  type: string
                  #                  format: password
                  example: password123
      responses:
        '200':
          description: OK
          content:
            application/json: { }
        '401':
          description: Unauthorized
          content:
            application/problem+json: { }
        '500':
          $ref: "#/components/responses/InternalServerErrorResponse"
  /logout:
    post:
      description: ログアウトをします
      tags: [ login-logout ]
      operationId: logout
      security:
        - csrfProtectionHeader: [ ]
        - csrfProtectionCookie: [ ]
      responses:
        '200':
          description: OK
          content:
            application/json: { }
        '500':
          $ref: "#/components/responses/InternalServerErrorResponse"
  /users:
    post:
      description: ユーザーを登録します
      tags: [ 　users　 ]
      operationId: createUser
      security:
        - csrfProtectionHeader: [ ]
        - csrfProtectionCookie: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserForm"
      responses:
        '201':
          description: Created
          headers:
            Location:
              description: 作成されたユーザーのURI
              schema:
                type: string
                example: "/users/123"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDTO"
        '400':
          $ref: "#/components/responses/BadRequestResponse"
        '500':
          $ref: "#/components/responses/InternalServerErrorResponse"
  /articles:
    post:
      tags: [ articles ]
      summary: 記事を作成します
      description: body と title を指定して記事を作成します。ログインが必要です。
      operationId: createArticle
      responses:
        '201':
          description: Created
#          content:
#            application/json:
#              schema:

components:
  schemas:
    ErrorDetail:
      description: BadRequest エラーが発生したときのエラーの詳細
      type: object
      properties:
        pointer:
          description: エラーが発生したリクエストパラメーターの JSON ポインター
          type: string
          example: "#/username"
        detail:
          description: エラーの詳細
          type: string
          example: "ユーザー名は3文字以上32文字以内で入力してください"
    BadRequest:
      description: >
        リクエストの内容が不正な場合のエラーレスポンス。
        クライアントはエラーの内容を確認してリクエストを修正する必要があります。
        [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457.html) に準拠しています。
      type: object
      properties:
        type:
          type: string
          format: uri
        title:
          type: string
        status:
          type: integer
          format: int32
          default: 400
          example: 400
        detail:
          type: string
        instance:
          type: string
          format: uri
          example: /users
        errors:
          type: array
          items:
            $ref: "#/components/schemas/ErrorDetail"
    InternalServerError:
      type: object
      properties:
        type:
          type: string
          format: uri
          default: "about:blank"
        title:
          type: string
          default: "Internal Server Error"
        status:
          type: integer
          format: int32
          default: 500
        detail:
          type: string
          default: null
        instance:
          type: string
          format: uri
          default: null
    UserForm:
      type: object
      required:
        - username
        - password
      properties:
        username:
          description: >
            ユーザー名。
            使用できる文字は半角英小文字と数字、およびハイフン、アンダースコア、ドットです。
            長さは3文字以上32文字以内です。
            ハイフン・アンダースコア・ドットはユーザー名の先頭と末尾に使用できません。
          type: string
          minLength: 3
          pattern: '^[a-z0-9][a-z0-9_.-]{1,30}[a-z0-9]$'
          maxLength: 32
          example: username123
        password:
          description: パスワード。10文字以上255文字以内
          type: string
          format: password
          minLength: 10
          maxLength: 255
          example: password123
    UserDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 123
        username:
          type: string
          example: username123
  responses:
    BadRequestResponse:
      description: BadRequest
      content:
        application/probrem+json:
          schema:
            $ref: "#/components/schemas/BadRequest"
    InternalServerErrorResponse:
      description: InternalServerError
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/InternalServerError"
  securitySchemes:
    csrfProtectionHeader:
      description: >
        CSRF 対策に利用するヘッダー。
        Cookie の XSRF-TOKEN の値を設定する必要があります。
      type: apiKey
      in: header
      name: X-XSRF-TOKEN
    csrfProtectionCookie:
      description: >
        CSRF 対策に利用する Cookie。
        XSRF-TOKEN Cookie は `GET /csrf-cookie` で取得できます。
      type: apiKey
      in: cookie
      name: XSRF-TOKEN
